image: node:20.8.0-bookworm

variables:
  GIT_STRATEGY: clone
  GIT_DEPTH: "0"

cache:
  paths:
    - node_modules/

build:
  script:
    - ./install.sh
    - export PATH=$PATH:~/.greycat/bin
    # build backend
    - greycat test
    - greycat build
    # build frontend
    - npm install -g pnpm
    - pnpm install
    - pnpm lint
    - pnpm build
    # prepare packaging
    - mv dist webroot && cp ~/.greycat/bin/greycat greycat && cp -R ~/.greycat/webroot/explorer webroot
    - echo "GREYCAT_MODE=serve" > .env && echo "GREYCAT_WEBROOT=webroot" >> .env && echo "GREYCAT_UNSECURE=true" >> .env

  artifacts:
    when: on_success
    expire_in: 1 week
    paths:
      - greycat
      - webroot
      - project.gcp
      - .env
