variables:
  GIT_STRATEGY: clone
  GIT_DEPTH: "0"

stages:
  - build
  - package

build:
  stage: build
  image: node:20.8.1-bookworm
  script:
    - source install.sh
    - export PATH=$PATH:~/.greycat/bin
    # build backend
    - printf $(greycat build-version) > build_version
    - greycat test
    - greycat build
    # build frontend
    - npm install -g pnpm
    - pnpm install
    - pnpm lint
    - pnpm build
    # prepare packaging
    - mkdir package && cd package 
    - mv ../dist webroot && cp ../project.gcp . && cp -R ~/.greycat/webroot/explorer webroot
    - echo "GREYCAT_MODE=serve" > .env && echo "GREYCAT_WEBROOT=webroot" >> .env && echo "GREYCAT_UNSECURE=true" >> .env
    - curl -qsL https://get.greycat.io/files/core/${GREYCAT_BRANCH}/${GREYCAT_CORE_VERSION_X64_LINUX}.zip -o tmp.zip && unzip -d ${GREYCAT_DIR} -oqq tmp.zip && rm tmp.zip
    - cp ~/.greycat/bin/greycat greycat && tar czf ../x64-linux.tar.gz .
    - curl -qsL https://get.greycat.io/files/core/${GREYCAT_BRANCH}/${GREYCAT_CORE_VERSION_ARM64_LINUX}.zip -o tmp.zip && unzip -d ${GREYCAT_DIR} -oqq tmp.zip && rm tmp.zip
    - cp ~/.greycat/bin/greycat greycat && tar czf ../arm64-linux.tar.gz .
    # - curl -qsL https://get.greycat.io/files/core/${GREYCAT_BRANCH}/${GREYCAT_CORE_VERSION_X64_APPLE}.zip -o tmp.zip && unzip -d ${GREYCAT_DIR} -oqq tmp.zip && rm tmp.zip
    # - cp ~/.greycat/bin/greycat greycat && tar czf ../x64-apple.tar.gz .
    # - curl -qsL https://get.greycat.io/files/core/${GREYCAT_BRANCH}/${GREYCAT_CORE_VERSION_ARM64_APPLE}.zip -o tmp.zip && unzip -d ${GREYCAT_DIR} -oqq tmp.zip && rm tmp.zip
    # - cp ~/.greycat/bin/greycat greycat && tar czf ../arm64-apple.tar.gz .
    # - rm greycat
    # - curl -qsL https://get.greycat.io/files/core/${GREYCAT_BRANCH}/${GREYCAT_CORE_VERSION_X64_WINDOWS}.zip -o tmp.zip && unzip -d ${GREYCAT_DIR} -oqq tmp.zip && rm tmp.zip
    # - cp ~/.greycat/bin/greycat.exe greycat.exe && tar czf ../x64-windows.tar.gz .
    # - curl -qsL https://get.greycat.io/files/core/${GREYCAT_BRANCH}/${GREYCAT_CORE_VERSION_ARM64_WINDOWS}.zip -o tmp.zip && unzip -d ${GREYCAT_DIR} -oqq tmp.zip && rm tmp.zip
    # - cp ~/.greycat/bin/greycat.exe greycat.exe && tar czf ../arm64-windows.tar.gz .
  artifacts:
    when: on_success
    expire_in: 1 week
    paths:
      - build_version
      - x64-linux.tar.gz
      - arm64-linux.tar.gz
      # - x64-apple.tar.gz
      # - arm64-apple.tar.gz
      # - x64-windows.tar.gz
      # - arm64-windows.tar.gz
  cache:
    paths:
      - node_modules/

package:
  stage: package
  image: quay.io/podman/stable:v4.7.0
  when: manual
  script:
    - build_version=`cat build_version`
    - podman build -t oci.datathings.com/greycat/template/web:${build_version} .
    #- docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    #- docker push oci.datathings.com/greycat/template/web:${build_version}
