image: node:20.8.0-bookworm

variables:
  GIT_STRATEGY: clone
  GIT_DEPTH: "0"

cache:
  paths:
    - node_modules/

build:
  script:
    - source install.sh
    - export PATH=$PATH:~/.greycat/bin
    # build backend
    - greycat build-version
    - greycat test
    - greycat build
    # build frontend
    - npm install -g pnpm
    - pnpm install
    - pnpm lint
    - pnpm build
    # prepare packaging
    - echo $GREYCAT_CORE_VERSION_ARCH
    - mv dist webroot && cp ~/.greycat/bin/greycat greycat && cp -R ~/.greycat/webroot/explorer webroot
    - echo "GREYCAT_MODE=serve" > .env && echo "GREYCAT_WEBROOT=webroot" >> .env && echo "GREYCAT_UNSECURE=true" >> .env
    - curl -qsL https://get.greycat.io/files/core/${GREYCAT_BRANCH}/$(printf "${GREYCAT_CORE_VERSION}" | sed "s/\//\/x64-windows\//").zip -o tmp.zip && unzip -d ${GREYCAT_DIR} -oqq tmp.zip && rm tmp.zip
    - curl -qsL https://get.greycat.io/files/core/${GREYCAT_BRANCH}/$(printf "${GREYCAT_CORE_VERSION}" | sed "s/\//\/arm64-windows\//").zip -o tmp.zip && unzip -d ${GREYCAT_DIR} -oqq tmp.zip && rm tmp.zip
  artifacts:
    when: on_success
    expire_in: 1 week
    paths:
      - greycat
      - webroot
      - project.gcp
      - .env
