image: node:20.8.0-bookworm

variables:
  GIT_STRATEGY: clone
  GIT_DEPTH: "0"
  GREYCAT_CORE_BRANCH: "dev"
  GREYCAT_CORE_MAJOR: "6.3"
  GREYCAT_CORE_VERSION: "6.3.86-dev"
  GREYCAT_LANG_VERSION: "6.3.5-dev"

cache:
  paths:
    - node_modules/

build:
  script:
    - curl -qsL https://get.greycat.io/files/core/${GREYCAT_CORE_BRANCH}/x86-linux/${GREYCAT_CORE_MAJOR}/${GREYCAT_CORE_VERSION}.zip -o tmp.zip && unzip -d ~/.greycat -oqq tmp.zip
    - curl -qsL https://get.greycat.io/files/lang/${GREYCAT_CORE_BRANCH}/${GREYCAT_CORE_MAJOR}/${GREYCAT_LANG_VERSION}.zip -o tmp.zip && unzip -d ~/.greycat -oqq tmp.zip
    - export PATH=$PATH:~/.greycat/bin
    # build backend
    - greycat test
    - greycat build
    # build frontend
    - npm install -g pnpm
    - pnpm install
    - pnpm lint
    - pnpm build
    # prepare packaging
    - mv dist webroot && cp ~/.greycat/bin/greycat greycat
    - echo "GREYCAT_MODE=serve" > .env && echo "GREYCAT_WEBROOT=webroot" >> .env && echo "GREYCAT_UNSECURE=true" >> .env

  artifacts:
    when: on_success
    expire_in: 1 week
    paths:
      - greycat
      - webroot
      - project.gcp
      - .env
