image: node:20.8.0-bookworm

variables:
  GIT_STRATEGY: clone
  GIT_DEPTH: "0"
  GREYCAT_CORE_BRANCH: "dev"
  GREYCAT_CORE_MAJOR: "6.3"
  GREYCAT_CORE_VERSION: "6.3.86-dev"
  GREYCAT_LANG_VERSION: "6.3.5-dev"

# This folder is cached between builds
# https://docs.gitlab.com/ee/ci/yaml/index.html#cache
cache:
  paths:
    - node_modules/

build:
  script:
    - curl -qsL https://get.greycat.io/files/core/${GREYCAT_CORE_BRANCH}/x86-linux/${GREYCAT_CORE_MAJOR}/${GREYCAT_CORE_VERSION}.zip -o tmp.zip && unzip -d . -oqq tmp.zip
    - curl -qsL https://get.greycat.io/files/lang/${GREYCAT_CORE_BRANCH}/${GREYCAT_CORE_MAJOR}/${GREYCAT_LANG_VERSION}.zip -o tmp.zip && unzip -d . -oqq tmp.zip
    - ./bin/greycat test
    - ./bin/greycat build
    - npm install -g pnpm
    - pnpm install
    #- pnpm lint
    - pnpm build
    - mv dist webroot
  artifacts:
    when: on_success
    expire_in: 1 week
    paths:
      - webroot
      - project.gcp
