image: oci.datathings.com/greycat/build/js:1.0.8-main

variables:
  GIT_STRATEGY: clone
  GIT_DEPTH: "0"

stages:
  - test
  - build

before_script:
  - export VERSION=`git2version -s`

# This folder is cached between builds
# https://docs.gitlab.com/ee/ci/yaml/index.html#cache
cache:
  paths:
    - node_modules/

test:
  stage: test
  script:
    - curl -fsSL https://get.greycat.io/install.sh | bash
    - greycat test

build:
  stage: build
  script:
    |
     sed -i -e 's/"version":\\s*"0.0.0"/"version": "${VERSION}"/g' package.json
     pnpm install
     pnpm build
  artifacts:
    when: on_success
    expire_in: '30 days'
    paths:
      - dist
